[package]

name = "rand"
version = "0.3.14"
authors = ["The Rust Project Developers"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/rust-lang/rand"
documentation = "https://doc.rust-lang.org/rand"
homepage = "https://github.com/rust-lang/rand"
description = """
Random number generators and other randomness functionality.
"""
keywords = ["random", "rng"]

[dependencies]
libc = { version = "0.2", optional = true }
core_io = { version = "0.0", optional = true } # enable use of read module on not(std)

[features]
# default = ["std"]
std = ["libc"]
box = [] # enable use of Box on not(std), requires alloc crate and feature
vec = [] # enable use of Vec on not(std), requires collections crate and feature

[dev-dependencies]
log = "0.3.0"
